CATEGORIES = [
    "Microcontrollers",
    "Mini Computers",
    "Drone Components",
    "Batteries and Accessories",
    "Cables (USB, Display, Data)",
    "Chargers and Power Cables",
    "Jumper Wires",
    "Electrical Appliances",
    "DIY Tools",
    "Hardware Accessories",
    "Network Devices and Cables",
    "Robotics Components",
    "Motors and Motor Drivers",
    "Electronic Components",
    "Measuring Instruments",
    "Stationery",
    "3D Printing Tools",
]
